services:
  iotgomq-pre_handler:
    build:
      context: ../../
      dockerfile: deploy/IotGoMQ.Dockerfile
    image: go-iot-mq:latest
    ports:
      - 8001:19000
    volumes:
       - ./mq/config/app-local-pre_handler.yml:/app/app-local-pre_handler.yml
    entrypoint: ["/app/main", "-config", "/app/app-local-pre_handler.yml"]
    networks:
      - iot-net
  iotgomq-calc_handler:
    image: go-iot-mq:latest
    ports:
      - 8002:19000
    volumes:
       - ./mq/config/app-local-calc.yml:/app/app-local-calc.yml
    entrypoint: ["/app/main", "-config", "/app/app-local-calc.yml"]
    networks:
      - iot-net
  iotgomq-waring_handler:
    image: go-iot-mq:latest
    ports:
      - 8003:19000
    volumes:
       - ./mq/config/app-local-waring_handler.yml:/app/app-local-waring_handler.yml
    entrypoint: ["/app/main", "-config", "/app/app-local-waring_handler.yml"]
    networks:
      - iot-net
  iotgomq-wd_handler:
    image: go-iot-mq:latest
    ports:
      - 8004:19000
    volumes:
       - ./mq/config/app-local-wd.yml:/app/app-local-wd.yml
    entrypoint: ["/app/main", "-config", "/app/app-local-wd.yml"]
    networks:
      - iot-net
  iotgoproject:
    build:
      context: ../../
      dockerfile: deploy/IotGoProject.Dockerfile
    image: go-iot-project:latest
    volumes:
      - ./iot-project/config/app-local.yml:/app/app-local.yml
    ports:
      - 8005:8080
    networks:
      - iot-net
  iotgomqtt1:
    build:
      context: ../../
      dockerfile: deploy/IotMQTT.Dockerfile
    image: go-iot-mqtt:latest
    entrypoint: ["/app/main", "-config", "/app/app-local.yml"]
    volumes:
      - ./mqtt/config/app-local.yml:/app/app-local.yml
    ports:
      - 8006:8081
    networks:
      - iot-net
  iotgomqtt2:
    image: go-iot-mqtt:latest
    ports:
      - 8007:8081
    entrypoint: ["/app/main", "-config", "/app/app-local2.yml"]
    volumes:
      - ./mqtt/config/app-local2.yml:/app/app-local2.yml
    networks:
      - iot-net
  iotgomqtt3:
    image: go-iot-mqtt:latest
    ports:
      - 8008:8081
    entrypoint: ["/app/main", "-config", "/app/app-local3.yml"]
    volumes:
      - ./mqtt/config/app-local3.yml:/app/app-local3.yml
    networks:
      - iot-net
networks:
  iot-net:
    driver: bridge
