global:
  scrape_interval:     15s
  evaluation_interval: 15s


scrape_configs:
#  - job_name: prometheus
#    static_configs:
#      - targets: ['172.17.0.1:9090']
  - job_name: iotgoproject
    static_configs:
      - targets: ['172.17.0.1:8005']
  - job_name: iotgomqtt1
    static_configs:
      - targets: ['172.17.0.1:8006']
  - job_name: iotgomqtt2
    static_configs:
      - targets: ['172.17.0.1:8007']
  - job_name: iotgomqtt3
    static_configs:
      - targets: ['172.17.0.1:8008']
  - job_name: iotgomq-pre_handler
    static_configs:
      - targets: ['172.17.0.1:8001']
  - job_name: calc_handler
    static_configs:
      - targets: ['172.17.0.1:8002']
  - job_name: iotgomq-waring_handler
    static_configs:
      - targets: ['172.17.0.1:8003']
  - job_name: iotgomq-iotgomq-wd_handler
    static_configs:
      - targets: ['172.17.0.1:8004']
