node_info:
  host: 172.17.0.1
  port: 29004
  name: mq1
  type: waring_delay_handler # pre_handler、 waring_handler、 calc_queue、waring_delay_handler


redis_config:
  host: 172.17.0.1
  port: 6379
  db: 10
  password: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81


mq_config:
  host: 172.17.0.1
  port: 5672
  username: guest
  password: guest
influx_config:
  host: 172.17.0.1
  port: 8086
  token: mytoken
  org: myorg
  bucket: mybucket
mongo_config:
  host: 172.17.0.1
  port: 27017
  username: admin
  password: admin
  db: iot
  collection: calc
  waring_collection: waring
  script_waring_collection: script_waring
