global:
  scrape_interval:     15s
  evaluation_interval: 15s


scrape_configs:
#  - job_name: prometheus
#    static_configs:
#      - targets: ['172.17.0.1:9090']
  - job_name: iotgoproject
    static_configs:
      - targets: ['172.17.0.1:8005']
        labels:
          namespace: iot-go-project
          pod: iot-go-project
          instance: iot-go-project
  - job_name: iotgomqtt1
    static_configs:
      - targets: ['172.17.0.1:8006']
        labels:
          namespace: iot-mqtt
          pod: iot-mqtt1
          instance: iot-mqtt1
  - job_name: iotgomqtt2
    static_configs:
      - targets: ['172.17.0.1:8007']
        labels:
          namespace: iot-mqtt
          pod: iot-mqtt2
          instance: iot-mqtt2
  - job_name: iotgomqtt3
    static_configs:
      - targets: ['172.17.0.1:8008']
        labels:
          namespace: iot-mqtt
          pod: iot-mqtt3
          instance: iot-mqtt3
  - job_name: iotgomq-pre_handler
    static_configs:
      - targets: ['172.17.0.1:8001']
        labels:
          namespace: iot-mq
          pod: iot-mq-pre_handler
          instance: iot-mq-pre_handler
  - job_name: calc_handler
    static_configs:
      - targets: ['172.17.0.1:8002']
        labels:
          namespace: iot-mq
          pod: iot-mq-calc_handler
          instance: iot-mq-calc_handler
  - job_name: iotgomq-waring_handler
    static_configs:
      - targets: ['172.17.0.1:8003']
        labels:
          namespace: iot-mq
          pod: iot-mq-waring_handler
          instance: iot-mq-waring_handler
  - job_name: iotgomq-wd_handler
    static_configs:
      - targets: ['172.17.0.1:8004']
        labels:
          namespace: iot-mq
          pod: iot-mq-wd_handler
          instance: iot-mq-wd_handler



  - job_name: iotgomq-pre_handler-1
    static_configs:
      - targets: ['172.17.0.1:10000']
        labels:
          namespace: iot-mq
          pod: iot-mq-pre_handler-1
          instance: iot-mq-pre_handler-1

  - job_name: iotgomq-pre_handler-2
    static_configs:
      - targets: ['172.17.0.1:10001']
        labels:
          namespace: iot-mq
          pod: iot-mq-pre_handler-2
          instance: iot-mq-pre_handler-2

  - job_name: iotgomq-pre_handler-3
    static_configs:
      - targets: ['172.17.0.1:10002']
        labels:
          namespace: iot-mq
          pod: iot-mq-pre_handler-3
          instance: iot-mq-pre_handler-3