node_info:
  port: 8080
  host: 192.168.3.101
redis_config:
  host: 192.168.3.101
  port: 6379
  db: 10
  password: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81

mq_config:
  host: 192.168.3.101
  port: 5672
  username: guest
  password: guest
influx_config:
  host: 192.168.3.101
  port: 8086
  token: mytoken
  org: myorg
  bucket: mybucket

mysql_config:
  username: app
  password: iot123456
  host: 192.168.3.101
  port: 3306
  dbname: iot
mongo_config:
  host: 192.168.3.101
  port: 27017
  username: admin
  password: admin
  db: iot
  collection: calc
  waring_collection: waring
  script_waring_collection: script_waring
